### ISSUE TITLE
type "github.com/anacrolix/utp".Addr does not exist

### ISSUE THREAD

**Issue by keks** [ipfs/go-libp2p-transport#12]
This library uses `"github.com/anacrolix/utp".Addr`, which does not exist, [here](https://github.com/libp2p/go-libp2p-transport/blob/master/utp.go#L171) and [here](https://github.com/libp2p/go-libp2p-transport/blob/master/utp.go#L208). What is this about?

**Comment by whyrusleeping** [comment]
@keks we use an old version of that library. We're actually planning on making the utp code in this package move into its own separate package anyways. 

If you have gx and gx-go installed, you can run `gx install && gx-go rewrite` and it will rewrite the imports to use the vendored code

**Comment by keks** [comment]
it's not used anymore. closing.
