### ISSUE TITLE
Add alternative to `Accept`, `SetConnHandler`

### ISSUE THREAD

**Issue by whyrusleeping** [ipfs/go-libp2p-transport#8]
We already have the `SetConnHandler` interface in other parts of libp2p, and some transports (websockets) fit much more nicely with this style. We should consider adding that interface as an optional way to consume incoming connections

**Comment by jbenet** [comment]
Yeah it's a nice handler. Though can't we make this a generic thing on top
of any accept interface? (You know if yo had generics...)

**Comment by jbenet** [comment]
Go*.

Though I wouldn't be opposed as an idiomatic adaptation.

**Comment by Stebalien** [comment]
One issue with interfaces like this is back-pressure; there's no way to provide back-pressure from a callback.

**Comment by Kubuxu** [comment]
You can limit the number of callbacks you are running at a time but this requires synchronization.

**Comment by Stebalien** [comment]
Unless done very carefully, that tends to either:

1. Just leave a bunch of go routines hanging around (when the event loop calls `go handler(conn)`).
2. Deadlocks everything (when the event loop calls `handler(conn)` directly).

To do this properly, we'd have to ensure that all implementations have separate, buffered accept loops.

**Comment by ghost** [comment]
Reviving this for the new year.  Labeled enhancement to indicate buffered accept loops (if we want to do this).  Discuss...

**Comment by Stebalien** [comment]
We can probably close this (libp2p was refactored after this discussion). The transport "upgrader" now implements a limited, buffered accept loop for accepting and upgrading incoming connections. The swarm's accept loop isn't buffered but it just dispatches new connections to new goroutines.
